### ISSUE TITLE
Front end with sample seed data has errors

### ISSUE THREAD

**Issue by evmiguel** [w3c/aria-at-app#505] opened 2023-02-27 15:43 UTC
When I populate a fresh database installation with `yarn workspace server db-populate-sample-data:dev;`, the Reports page and Candidate Tests page contain errors. See screenshots for errors:

- Error on Reports Page:
  - In the screenshot, the support levels are at 0%. The levels should be greater than 0.   
  - <img width="1281" alt="In the screenshot, the support levels are at 0%. The levels should be greater than 0.  " src="https://user-images.githubusercontent.com/2789098/221609236-56df99fe-6453-4455-8bb6-4841fc5b4b91.png" >

- Error on Candidate Tests Page:
  - In the screenshot, the results summaries show `NaN assertions failed across NaN tests`. The NaNs should be numbers. 
  - <img width="1271" alt="In the screenshot, the results summaries show `NaN assertions failed across NaN tests`. The NaNs should be numbers." src="https://user-images.githubusercontent.com/2789098/221609044-46e2ad11-685c-4cea-a5a8-9016a909916b.png">

**Comment by alflennik** [comment] 2023-02-27 17:49
@evmiguel Thanks for making an issue for this. It's caused by a performance enhancement @howard-e added which denormalizes some of the database data under a "metrics" field. Perhaps we can augment the model code to automatically populate the metrics field when a given row is created or updated.

Also @evmiguel would you be so kind to write some alt text for the screenshots, I'm sure that would be appreciated!

**Comment by alflennik** [comment] 2023-05-01 14:51
Thank you Erika! Now that we fixed the issue we can close this.

**Closed as completed by alflennik** 2023-05-01 14:51 UTC
