### ISSUE TITLE
Add 'Raise an Issue' button to test plan view pages

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#1249] opened 2024-10-21 15:01 UTC
Similar to report pages, Add a button for raising an issue to test plan view pages, e.g., [Action Menu Button Example Using aria-activedescendant Test Plan V22.03.17 | ARIA-AT](https://aria-at.w3.org/test-review/2407).

**Comment by ccanash** [comment] 2024-12-11 15:27
Closing as duplicate of #1241

**Closed by ccanash** 2024-12-11 15:27 UTC
Labels: enhancement
