### ISSUE TITLE
Test Management: Test Plan Summary shows incorrect phase values

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#584] opened 2023-03-29 00:29 UTC
The [Test Management Test Plan Summary](https://aria-at.w3.org/test-management#main) shows incorrect working mode phases.

It currently shows only one plan (Alert) in the candidate phase but there are actually 8 plans in the candidate phase (See Candidate Tests page).

Note: The Candidate Tests page incorrectly shows that the "Disclosure Navigation Menu Example" is a Candidate test plan. That is an error, and we don't have a way to correct it.

The list of test plans that are visible on the Candidate Tests page should match the plans that are shown as candidate on the test management page. Changing the phase on the test management phase should change test plan visibility any place in the app where visibility depends on its phase in the working mode.

**Comment by howard-e** [comment] 2023-04-12 15:55
> It currently shows only one plan (Alert) in the candidate phase but there are actually 8 plans in the candidate phase (See Candidate Tests page).

It currently shows them all as being in the `DRAFT` phase, `Alert` included so something may have changed since this was posted but, the same explanation applies. What’s happening here is that the Test Management page is displaying the collection of Test Plan Reports across the different AT + Browser combinations which are using the latest AT versions (and implicitly, the most recently created Test Plan Reports). This combination of Test Plan Reports is what is being used to then derive a ‘Test Plan’ as the application defines it, which is conceptually different from what the Working Mode now expects as has been described over the recent weeks.

From what I can see, the `Alert` plan’s `DRAFT` status is based on the `JAWS + Chrome, published Mar 20, 2023`, the `NVDA + Chrome, published Dec 8, 2022` and the `VoiceOver + Safari, published Dec 8, 2022` Test Plan Reports which are currently located in on the [Test Queue Page](https://aria-at.w3.org/test-queue) which means they are all `DRAFT`. What I described is also reflected in the introduction of the current [Test Management Page](https://aria-at.w3.org/test-management). Another nuance here is that even if any SINGLE items of the Test Plan Reports that I noted, were then promoted to `CANDIDATE` or `RECOMMENDED`, it would still be identified as `DRAFT` because the value will be determined based on the lowest phase in the collection of Test Plan Reports but maybe we could reverse this logic in the interim?

But then the purpose of the phase transition actions would be questionable as it’s meant to assist the admin with easily promoting the Test Plan Reports with the latest AT Versions. When this was being done, it was meant to be a subset of what has been proposed at [Mockups for Test Plan Management, Test Queue, and Candidate Test Plans](https://github.com/w3c/aria-at-app/issues/518) but perhaps the chosen subset of actions implemented was too premature. Some suggested actions / mitgations here until the additional structure changes are accounted for follows:
1. We consider making this page informational for now. I'm not sure how much usage is intended for it as well right now given that it is still missing some of the wider talked about admin actions. That means removing the phase update actions and have it just show the combined state of the latest set of Test Plan Reports (lowest phase across the Test Plan Reports using their respective latest AT versions will still overwrite the priority)
2. We consider displaying additional information on the page to make the summary clearer as it aligns with the present structure and not to force it to what is expected of the structure which has not been properly designed for. So this could mean outlining the current phase of the individual Test Plan Reports', AT + Browser combinations currently forcing the phase being displayed on the summary rows currently, as well as displaying what is the current "most updated phase", in this instance, `CANDIDATE` for the Alert pattern for example.
3. The previous 2 are simply mitigations and it would be best to get to the restructuring how the application derives a Test Plan which means a shift in the database design in the coming weeks.

> Note: The Candidate Tests page incorrectly shows that the “Disclosure Navigation Menu Example” is a Candidate test plan. That is an error, and we don’t have a way to correct it.

To be clear, is the problem that this should still be in `DRAFT`? If so, there is a `Mark as ...` action on the Candidate Tests page which can be used to change the phase and reverting it to `DRAFT` is possible.

> The list of test plans that are visible on the Candidate Tests page should match the plans that are shown as candidate on the test management page. Changing the phase on the test management phase should change test plan visibility any place in the app where visibility depends on its phase in the working mode.

This stems from previous conversations which show a conceptual misunderstanding between what the application is displaying and what the expected behavior is. This indicates that the understanding is that a single Test Plan, being a combination of all accounted for ATs of any arbitrary pattern exists and is being continuously promoted / demoted (or some state of being restarted). This logic conflicts with how the combination of "Test Plan Report" entities are actually designed in the application. This will continue to be further discussed and addressed in upcoming iterations.

**Comment by lolaodelola** [comment] 2023-05-23 14:51
@howard-e Is this (temporarily) resolved by #499?

**Comment by howard-e** [comment] 2023-05-23 15:48
No, with #499 being merged (which included #500), it temporarily solved #522.

An agreement arrived at in other discussions, is to move forward with suggestion no. 2 from https://github.com/w3c/aria-at-app/issues/584#issuecomment-1505526697. This is also reflected in [recent mockups](https://github.com/w3c/aria-at-app/issues/518#issuecomment-1555049607) for the Data Management page.

**Comment by mcking65** [comment] 2023-09-26 20:14
Reviewed behavior in staging. This issue is resolved and can be closed after deployment.

**Comment by ccanash** [comment] 2023-10-03 18:10
Released to production

**Closed by ccanash** 2023-10-03 18:10 UTC
Labels: bug
